// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gumfa.services.ProductAPICQRS.Data;

#nullable disable

namespace gumfa.services.EmployeAPICQRS.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250726213607_Added employe table")]
    partial class Addedemployetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gumfa.services.ProductAPICQRS.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("EMPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            EMPCode = "EMP001",
                            IsActive = true,
                            Name = "Employee A"
                        },
                        new
                        {
                            EmployeeID = 2,
                            EMPCode = "EMP002",
                            IsActive = true,
                            Name = "Employee B"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
