// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gumfa.services.MasterAPI.Data;

#nullable disable

namespace gumfa.services.MasterAPI.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20250724073544_added master db")]
    partial class addedmasterdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gumfa.services.MasterAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("54466f17-02af-48e7-8ed3-5a4a8bfacf6f"),
                            Description = "Product Decription 001",
                            IsActive = true,
                            MRP = 100m,
                            ProductName = "Product 001"
                        },
                        new
                        {
                            ProductID = new Guid("ea294873-7a8c-4c0f-bfa7-a2eb492cbf8c"),
                            Description = "Product Decription 001",
                            IsActive = true,
                            MRP = 100m,
                            ProductName = "Product 001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
